name: 'Camel K'
description: 'Provides a Kubernetes playground environment and Camel K tools'
inputs:
  cluster:
    description: 'The type of cluster to start ("kubernetes", "openshift", "none")'
    required: true
    default: 'kubernetes'
  kindVersion:
    description: 'The version of KinD to use'
    required: true
    default: 'v0.6.1'
  openshiftVersion:
    description: 'The version of OpenShift to use'
    required: true
    default: 'v3.11.0'
  version:
    description: 'The version of Camel K to use'
    required: true
    default: '1.0.0-RC1'
  
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'octagon'  
  color: 'yellow'
