name: 'Camel K'
description: 'Provides a Kubernetes playground environment and Camel K tools'
inputs:
  kindVersion:
    description: 'The version of KinD to use'
    required: true
    default: 'v0.6.1'
  version:
    description: 'The version of Camel K to use'
    required: true
    default: '1.0.0-M4'
runs:
  using: 'node12'
  main: 'github-action/index.js'
branding:
  icon: 'octagon'  
  color: 'green'
